### ISSUE TITLE
Wrong icon printing in Windows Phone 8.1 devices

### ISSUE THREAD

**Issue by mowcixo** [driftyco/ionicons#144]
In Internet Explorer 11 for Windows Phone, the icons prints as a rectangle. Editing the **@font-face** in **ionicons/scss/_ionicons-font.scss** like this:

 ```scss
@font-face {
  font-family: $ionicons-font-family;
  src:url("#{$ionicons-font-path}/ionicons.eot");
  src:url("#{$ionicons-font-path}/ionicons.eot") format("embedded-opentype"),
   url("#{$ionicons-font-path}/ionicons.ttf") format("truetype"),
   url("#{$ionicons-font-path}/ionicons.woff") format("woff"),
   url("#{$ionicons-font-path}/ionicons.svg") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

Basically removing the query string in font file paths, solves the problem. I don't know if its a right change, but I suggest it as a solution.
